//THIS FUNCTION ADD MINUTES TO THE APPOINTMENTS
export const addMinutes = (time, minutes) => {//THIS FUNCTION GET TWO PARAMETERS : TIME IS A STRING WITH HH:MM FORMAT AND MINUTES IS A NUMBER OF MINUTES THAT I GOING TO ADD
    
    const [hour, min] = time.split(':').map(Number);//DIVIDE THE STRING INTO AN ARRAY AND CONERT THE VALUE FROM STRING TO NUMBER AND THE CONST DESESTRUCTURED THE ARRAY
    const date = new Date();//THIS CREATES AN OBJECT DATE WITH THE DATE AND CURRENT HOUR OF THE SYSTEM, THIS IS A TOOL TO MANIPULATE HOURS

    date.setHours(hour);//THIS CHANGES THE HOUR OF THE OBJECT TO THE HOUR THAT COMES FROM TIME
    date.setMinutes(min + minutes);//THIS ADD THE ORIGINAL MINUTES + MINUTES THAT I WANT TO ADD, IF THE MINUTES ARE MORE THAN 60 IT AUTOMATILLY AJUST THE HOUR

    return date.toTimeString().slice(0, 5);//THIS RETURNS THE FINAL RESULT AS A STRING
}